# Generated by Django 6.0.6 on 2026-06-28 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_activitylog_if_exists(apps, schema_editor):
    """Drop ActivityLog table if it exists to avoid conflicts"""
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS properties_activitylog CASCADE")
            print("Dropped ActivityLog table to avoid conflicts")
    except Exception as e:
        print(f"Error dropping ActivityLog (may not exist): {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_broker_custom_ads_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_activitylog_if_exists, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='propertydallalassignment',
            unique_together=set(),
        ),
    ]
