# Generated by Django 6.0.6 on 2026-06-28 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_conflicting_tables(apps, schema_editor):
    """Drop tables that might cause conflicts in later migrations"""
    try:
        with schema_editor.connection.cursor() as cursor:
            # Drop ActivityLog if it exists
            cursor.execute("DROP TABLE IF EXISTS properties_activitylog CASCADE")
            print("Dropped ActivityLog table to avoid conflicts")
            
            # Also drop Hotel, Resort, Country, BrokerChannel tables if they exist to avoid conflicts
            cursor.execute("DROP TABLE IF EXISTS properties_hotel CASCADE")
            cursor.execute("DROP TABLE IF EXISTS properties_resort CASCADE")
            cursor.execute("DROP TABLE IF EXISTS properties_country CASCADE")
            cursor.execute("DROP TABLE IF EXISTS properties_brokerchannel CASCADE")
            print("Dropped Hotel, Resort, Country, BrokerChannel tables to avoid conflicts")
            
            # Drop conflicting columns from properties_property if they exist
            conflicting_columns = ['publication_end_date', 'expiry_date', 'is_pinned', 'pinned_until']
            for column in conflicting_columns:
                cursor.execute(f"""
                    ALTER TABLE properties_property DROP COLUMN IF EXISTS {column} CASCADE
                """)
            print(f"Dropped conflicting columns from properties_property: {', '.join(conflicting_columns)}")
    except Exception as e:
        print(f"Error dropping conflicting tables/columns: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_broker_custom_ads_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_conflicting_tables, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='propertydallalassignment',
            unique_together=set(),
        ),
    ]
