# Generated by Django 6.0.6 on 2026-07-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def create_model_if_not_exists(apps, schema_editor):
    # Check if table already exists using database-agnostic method
    table_names = connection.introspection.table_names()
    if 'properties_auctionparticipant' in table_names:
        # Table already exists, skip creation and field additions
        print("AuctionParticipant table already exists, skipping model creation")
        return True  # Return True to indicate table exists
    
    # Table doesn't exist, create it
    AuctionParticipant = apps.get_model('properties', 'AuctionParticipant')
    schema_editor.create_model(AuctionParticipant)
    print("Created AuctionParticipant table")
    return False  # Return False to indicate table was created


def add_fields_if_table_existed(apps, schema_editor):
    # This is a no-op - if table existed, we skip field additions
    # If table was just created, Django will handle field additions normally
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0067_auction_approval_status_auction_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_model_if_not_exists, migrations.RunPython.noop),
    ]
