# Generated by Django 5.2.17 on 2026-08-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_voice_interaction_log_if_exists(apps, schema_editor):
    """Drop ai_voice_interaction_log table if it exists to avoid conflicts"""
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS ai_voice_interaction_log CASCADE")
    except Exception as e:
        pass  # Silent failure


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0172_merge_20260815_0659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_voice_interaction_log_if_exists, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VoiceInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_ms', models.FloatField()),
                ('audio_quality_score', models.FloatField(blank=True, null=True)),
                ('recognized_text', models.TextField()),
                ('stt_confidence', models.FloatField(blank=True, null=True)),
                ('stt_language', models.CharField(default='ar-SA', max_length=10)),
                ('stt_success', models.BooleanField()),
                ('intent_detected', models.CharField(blank=True, max_length=50)),
                ('entities_extracted', models.JSONField(blank=True, default=dict)),
                ('command_recognized', models.CharField(blank=True, max_length=50)),
                ('response_text', models.TextField(blank=True)),
                ('tts_used', models.BooleanField(default=False)),
                ('tts_duration_ms', models.FloatField(blank=True, null=True)),
                ('interrupted', models.BooleanField(default=False)),
                ('user_corrected', models.BooleanField(default=False)),
                ('corrected_text', models.TextField(blank=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_voice_interaction_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
