# Generated by Django 5.2.17 on 2026-08-26 20:26

import django.db.models.deletion
import django.utils.timezone
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0192_ensure_superuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resortimage',
            options={'ordering': ['order'], 'verbose_name': 'صورة منتجع', 'verbose_name_plural': 'صور المنتجعات'},
        ),
        migrations.AlterModelOptions(
            name='resortvideo',
            options={'ordering': ['order'], 'verbose_name': 'فيديو منتجع', 'verbose_name_plural': 'فيديوهات المنتجعات'},
        ),
        migrations.RemoveField(
            model_name='resortinsideiraq',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resortinsideiraq',
            name='has_bbq',
        ),
        migrations.RemoveField(
            model_name='resortinsideiraq',
            name='has_kitchen',
        ),
        migrations.RemoveField(
            model_name='resortinsideiraq',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='resortinsideiraq',
            name='min_guests',
        ),
        migrations.RemoveField(
            model_name='resortoutsideiraq',
            name='has_bbq',
        ),
        migrations.RemoveField(
            model_name='resortoutsideiraq',
            name='has_kitchen',
        ),
        migrations.RemoveField(
            model_name='resortoutsideiraq',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='resortoutsideiraq',
            name='min_guests',
        ),
        migrations.AddField(
            model_name='resortimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='resortimage',
            name='resort_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.resortinsideiraq', verbose_name='المنتجع داخل العراق'),
        ),
        migrations.AddField(
            model_name='resortimage',
            name='resort_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.resortoutsideiraq', verbose_name='المنتجع خارج العراق'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='resortvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='resortvideo',
            name='resort_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.resortinsideiraq', verbose_name='المنتجع داخل العراق'),
        ),
        migrations.AddField(
            model_name='resortvideo',
            name='resort_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.resortoutsideiraq', verbose_name='المنتجع خارج العراق'),
        ),
        migrations.AddField(
            model_name='resortvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=properties.models.resort_image_path, verbose_name='صورة مصغرة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='وصف الشركة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='resortimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.resort_image_path, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='resortvideo',
            name='video',
            field=models.FileField(upload_to=properties.models.resort_video_path, verbose_name='الفيديو'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='description',
            field=models.TextField(verbose_name='وصف الشركة'),
        ),
    ]
