# Generated by Django 5.2.17 on 2026-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0193_alter_resortimage_options_alter_resortvideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecontract',
            name='broker_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contract_signatures/', verbose_name='توقيع الدلال'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='broker_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ توقيع الدلال'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contract_signatures/', verbose_name='توقيع العميل'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ توقيع العميل'),
        ),
    ]
