# Generated by Django 5.2.17 on 2026-08-27 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0194_realestatecontract_broker_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('independent', 'وكيل مستقل'), ('agency', 'وكيل وكالة'), ('consultant', 'مستشار')], default='independent', max_length=20, verbose_name='نوع الوكيل')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الرخصة')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرخصة')),
                ('office_address', models.TextField(blank=True, verbose_name='عنوان المكتب')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('commission_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت'), ('hybrid', 'مختلط')], default='percentage', max_length=20, verbose_name='نوع العمولة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('fixed_commission', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='العمولة الثابتة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('total_customers', models.IntegerField(default=0, verbose_name='إجمالي العملاء')),
                ('total_sales', models.IntegerField(default=0, verbose_name='إجمالي المبيعات')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة النجاح (%)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'وكيل',
                'verbose_name_plural': 'الوكلاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة'), ('saturday', 'السبت'), ('sunday', 'الأحد')], max_length=10, verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('max_appointments', models.IntegerField(default=1, verbose_name='الحد الأقصى للمواعيد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'فترة توافر',
                'verbose_name_plural': 'فترات التوافر',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('investor', 'مستثمر')], default='individual', max_length=20, verbose_name='نوع العميل')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('company_registration', models.CharField(blank=True, max_length=50, verbose_name='رقم التسجيل')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'هاتف'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب')], default='phone', max_length=20, verbose_name='طريقة التواصل المفضلة')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ku', 'کوردی')], default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('vip', 'VIP')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('blacklisted', 'محظور')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('total_properties_viewed', models.IntegerField(default=0, verbose_name='إجمالي العقارات المعروضة')),
                ('total_inquiries', models.IntegerField(default=0, verbose_name='إجمالي الاستفسارات')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='إجمالي المشتريات')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='إجمالي الإنفاق')),
                ('first_contact_date', models.DateField(blank=True, null=True, verbose_name='تاريخ أول تواصل')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تواصل')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر شراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'موعد', 'verbose_name_plural': 'المواعيد'},
        ),
        migrations.AlterModelOptions(
            name='brokerappointment',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'موعد دلال', 'verbose_name_plural': 'مواعيد الدلالين'},
        ),
        migrations.RemoveIndex(
            model_name='brokerappointment',
            name='properties__user_id_672cab_idx',
        ),
        migrations.RemoveField(
            model_name='realestatecontract',
            name='broker_signature',
        ),
        migrations.RemoveField(
            model_name='realestatecontract',
            name='broker_signed_at',
        ),
        migrations.RemoveField(
            model_name='realestatecontract',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='realestatecontract',
            name='client_signed_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='المدة (دقائق)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_minutes_before',
            field=models.IntegerField(default=60, verbose_name='دقائق قبل التذكير'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال التذكير'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='properties.appointment', verbose_name='تم إعادة الجدولة من'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='target_type',
            field=models.CharField(choices=[('property', 'عقار'), ('broker', 'دلال'), ('user', 'مستخدم')], default='property', max_length=20, verbose_name='نوع الهدف'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='reminder_minutes_before',
            field=models.IntegerField(default=60, verbose_name='دقائق قبل التذكير'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='properties.brokerappointment', verbose_name='تم إعادة الجدولة من'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('property_viewing', 'معاينة عقار'), ('phone_call', 'مكالمة هاتفية'), ('meeting', 'اجتماع'), ('video_call', 'مكالمة فيديو'), ('office_visit', 'زيارة المكتب')], max_length=30, verbose_name='نوع الموعد'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل'), ('no_show', 'لم يحضر'), ('rescheduled', 'تم إعادة الجدولة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='brokerappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='brokerappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', '-appointment_date'], name='properties__user_id_c8f820_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='properties__status_6cfa63_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['target_type', 'target_id'], name='properties__target__8f093f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['priority', 'appointment_date'], name='properties__priorit_6827a6_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerappointment',
            index=models.Index(fields=['broker', '-appointment_date'], name='properties__broker__a993cd_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerappointment',
            index=models.Index(fields=['user', '-appointment_date'], name='properties__user_id_c14f36_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerappointment',
            index=models.Index(fields=['priority', 'appointment_date'], name='properties__priorit_fef7a0_idx'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='properties.agent', verbose_name='الوكيل المخصص'),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='properties.broker', verbose_name='الدلال المخصص'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'is_verified'], name='properties__status_3c2744_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_type'], name='properties__agent_t_e46106_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['city', 'governorate'], name='properties__city_b5d012_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['-created_at'], name='properties__created_44a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['broker', 'day_of_week'], name='properties__broker__bf69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['is_available'], name='properties__is_avai_9fd394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('broker', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'priority'], name='properties__status_8d6153_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='properties__custome_4d5ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['assigned_broker'], name='properties__assigne_688890_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['assigned_agent'], name='properties__assigne_c699d5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='properties__created_3c242b_idx'),
        ),
    ]
