# Generated by Django 5.2.17 on 2026-08-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0195_agent_appointmentslot_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('updated', 'تعديل'), ('viewed', 'عرض'), ('archived', 'أرشفة'), ('restored', 'استرجاع'), ('deleted', 'حذف نهائي'), ('status_changed', 'تغيير الحالة'), ('document_added', 'إضافة وثيقة'), ('document_removed', 'حذف وثيقة'), ('payment_added', 'إضافة دفعة'), ('payment_updated', 'تعديل دفعة'), ('reminder_added', 'إضافة تذكير'), ('party_added', 'إضافة طرف'), ('party_updated', 'تعديل طرف')], max_length=30, verbose_name='العملية')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التنفيذ')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='القيم الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'سجل تدقيق عقد',
                'verbose_name_plural': 'سجلات تدقيق العقود',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('first_party', 'الطرف الأول'), ('second_party', 'الطرف الثاني'), ('third_party', 'طرف ثالث'), ('witness', 'شاهد'), ('guarantor', 'كفيل')], max_length=20, verbose_name='نوع الطرف')),
                ('party_role', models.CharField(choices=[('buyer', 'مشتري'), ('seller', 'بائع'), ('landlord', 'مؤجر'), ('tenant', 'مستأجر'), ('agent', 'وسيط'), ('broker', 'دلال'), ('other', 'أخرى')], max_length=20, verbose_name='دور الطرف')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('governorate', models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='contract_signatures/', verbose_name='صورة التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طرف عقد',
                'verbose_name_plural': 'أطراف العقود',
                'ordering': ['party_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='contractdocument',
            options={'ordering': ['page_number', '-uploaded_at'], 'verbose_name': 'وثيقة عقد', 'verbose_name_plural': 'وثائق العقود'},
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الملف'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='رقم الصفحة'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أرشف بواسطة'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='archived_reason',
            field=models.TextField(blank=True, verbose_name='سبب الأرشفة'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='contract_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان العقد'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='currency',
            field=models.CharField(choices=[('IQD', 'دينار عراقي'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي')], default='IQD', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='realestatecontract',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['page_number'], name='properties__page_nu_661380_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['is_archived'], name='properties__is_arch_988d42_idx'),
        ),
        migrations.AddField(
            model_name='contractauditlog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='properties.realestatecontract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='contractauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='نفذ بواسطة'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='properties.realestatecontract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_parties', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط'),
        ),
        migrations.AddIndex(
            model_name='contractauditlog',
            index=models.Index(fields=['contract', '-performed_at'], name='properties__contrac_c55ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='contractauditlog',
            index=models.Index(fields=['performed_by'], name='properties__perform_796209_idx'),
        ),
        migrations.AddIndex(
            model_name='contractauditlog',
            index=models.Index(fields=['action'], name='properties__action_be07ed_idx'),
        ),
        migrations.AddIndex(
            model_name='contractauditlog',
            index=models.Index(fields=['-performed_at'], name='properties__perform_88dc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['contract', 'party_type'], name='properties__contrac_198696_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['user'], name='properties__user_id_7bf204_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['phone'], name='properties__phone_caa1fb_idx'),
        ),
    ]
