# Generated by Django 5.2.17 on 2026-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0196_contractauditlog_contractparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecontract',
            name='duration_type',
            field=models.CharField(choices=[('temporary', 'عقد مؤقت'), ('permanent', 'عقد دائم')], default='temporary', max_length=20, verbose_name='مدة العقد'),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='contract_type',
            field=models.CharField(choices=[('sale', 'عقد بيع'), ('rent', 'عقد إيجار'), ('investment', 'عقد استثمار'), ('other', 'تصنيف آخر')], max_length=20, verbose_name='نوع العقد'),
        ),
    ]
