# Generated by Django 5.2.17 on 2026-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0198_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشركة')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('churned', 'Churned')], default='lead', max_length=20, verbose_name='المرحلة')),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=20, verbose_name='الأولوية')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة')),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('next_followup', models.DateTimeField(blank=True, null=True, verbose_name='المتابعة القادمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'جهة اتصال CRM',
                'verbose_name_plural': 'جهات اتصال CRM',
                'ordering': ['-created_at'],
            },
        ),
    ]
