# Generated by Django 5.2.17 on 2026-08-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0199_crmcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allows_companies',
            field=models.BooleanField(default=False, verbose_name='هل يسمح للشركات؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_families',
            field=models.BooleanField(default=True, verbose_name='هل يسمح للعوائل؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_pets',
            field=models.BooleanField(default=False, verbose_name='هل يسمح بالحيوانات؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_students',
            field=models.BooleanField(default=False, verbose_name='هل يسمح للطلاب؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='annual_rent',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قيمة الإيجار السنوي'),
        ),
        migrations.AddField(
            model_name='property',
            name='approximate_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموقع التقريبي'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم البناية'),
        ),
        migrations.AddField(
            model_name='property',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة الإنجاز إذا قيد الإنشاء'),
        ),
        migrations.AddField(
            model_name='property',
            name='complex_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المجمع السكني'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_issuing_authority',
            field=models.CharField(blank=True, max_length=200, verbose_name='جهة إصدار السند'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_from_main_road',
            field=models.CharField(blank=True, max_length=100, verbose_name='قرب العقار من الشارع العام'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_gas_station',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن محطة الوقود'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_hospital',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن المستشفى'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_market',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن السوق'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_mosque',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن المسجد'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_school',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن المدرسة'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_university',
            field=models.CharField(blank=True, max_length=100, verbose_name='مسافة عن الجامعة'),
        ),
        migrations.AddField(
            model_name='property',
            name='down_payment_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قيمة العربون'),
        ),
        migrations.AddField(
            model_name='property',
            name='facade_type',
            field=models.CharField(blank=True, choices=[('main_road', 'شارع رئيسي'), ('secondary_road', 'شارع فرعي'), ('internal', 'داخلي')], max_length=20, verbose_name='نوع الواجهة'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_in_building',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الطابق داخل البناية'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'غير مفروش'), ('furnished', 'مفروش'), ('semi_furnished', 'شبه مفروش')], max_length=20, verbose_name='حالة التأثيث'),
        ),
        migrations.AddField(
            model_name='property',
            name='furniture_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'متوسط'), ('poor', 'سيء'), ('none', 'بدون أثاث')], max_length=20, verbose_name='حالة الأثاث'),
        ),
        migrations.AddField(
            model_name='property',
            name='generator_amperage',
            field=models.CharField(blank=True, max_length=50, verbose_name='أمبير المولدة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_24_hour_electricity',
            field=models.BooleanField(default=False, verbose_name='خط سريع/24 ساعة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_air_conditioners',
            field=models.BooleanField(default=False, verbose_name='مكيفات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cctv_cameras',
            field=models.BooleanField(default=False, verbose_name='كاميرات مراقبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_central_ac',
            field=models.BooleanField(default=False, verbose_name='تكييف مركزي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_central_cooling',
            field=models.BooleanField(default=False, verbose_name='تبريد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_central_heating',
            field=models.BooleanField(default=False, verbose_name='تدفئة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_closed_garage',
            field=models.BooleanField(default=False, verbose_name='كراج مغلق'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_equipped_kitchen',
            field=models.BooleanField(default=False, verbose_name='مطبخ مجهز'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_fiber_internet',
            field=models.BooleanField(default=False, verbose_name='إنترنت فايبر'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_furniture',
            field=models.BooleanField(default=False, verbose_name='أثاث'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gas_supply',
            field=models.BooleanField(default=False, verbose_name='غاز'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_legal_issues',
            field=models.BooleanField(default=False, verbose_name='هل توجد مشاكل قانونية؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_national_electricity_line',
            field=models.BooleanField(default=False, verbose_name='خط كهرباء وطني'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_private_generator',
            field=models.BooleanField(default=False, verbose_name='مولدة خاصة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_satellite',
            field=models.BooleanField(default=False, verbose_name='ستلايت'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_gate',
            field=models.BooleanField(default=False, verbose_name='بوابة أمنية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_guard',
            field=models.BooleanField(default=False, verbose_name='حراسة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sewerage_system',
            field=models.BooleanField(default=False, verbose_name='صرف صحي'),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_electricity',
            field=models.BooleanField(default=False, verbose_name='شامل الكهرباء؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_generator',
            field=models.BooleanField(default=False, verbose_name='شامل المولدة؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_internet',
            field=models.BooleanField(default=False, verbose_name='شامل الإنترنت؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_water',
            field=models.BooleanField(default=False, verbose_name='شامل الماء؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='installment_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قيمة القسط'),
        ),
        migrations.AddField(
            model_name='property',
            name='installment_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='مدة التقسيط'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_corner_lot',
            field=models.BooleanField(default=False, verbose_name='ناصية'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_corner_property',
            field=models.BooleanField(default=False, verbose_name='عقار زاوية'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_mortgaged',
            field=models.BooleanField(default=False, verbose_name='هل العقار مرهون؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_registration_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='حالة التسجيل العقاري'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_issues_description',
            field=models.TextField(blank=True, verbose_name='وصف المشاكل القانونية'),
        ),
        migrations.AddField(
            model_name='property',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم رخصة المكتب أو الدلال'),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_rental_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='أقل مدة للإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قيمة الإيجار الشهري'),
        ),
        migrations.AddField(
            model_name='property',
            name='needs_renovation',
            field=models.BooleanField(default=False, verbose_name='هل يحتاج ترميم؟'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_elevators',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد المصاعد'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_facades',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد واجهات العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_installments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأقساط'),
        ),
        migrations.AddField(
            model_name='property',
            name='office_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المكتب العقاري'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_transfer_possible',
            field=models.BooleanField(default=True, verbose_name='إمكانية نقل الملكية'),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدًا'), ('installments', 'أقساط'), ('down_payment_installments', 'دفعة + أقساط')], max_length=30, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع الإجازة/الموافقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_square_meter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='سعر المتر المربع'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_commission',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='العمولة'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_deposit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تأمين/عربون الإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='sector_direction',
            field=models.CharField(blank=True, max_length=50, verbose_name='الجهة/القطاع'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='السعر الإجمالي'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الوحدة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_property_records', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة'),
        ),
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('unverified', 'غير متحقق'), ('under_review', 'قيد المراجعة'), ('verified', 'موثق'), ('rejected', 'مرفوض')], default='unverified', max_length=20, verbose_name='حالة التحقق')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='تم التحقق من هوية المعلن')),
                ('ownership_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الملكية')),
                ('location_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الموقع')),
                ('images_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الصور')),
                ('price_verified', models.BooleanField(default=False, verbose_name='تم التحقق من السعر')),
                ('verification_notes', models.TextField(blank=True, verbose_name='ملاحظات التحقق')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='verification_documents/', verbose_name='وثيقة الهوية')),
                ('ownership_document', models.FileField(blank=True, null=True, upload_to='verification_documents/', verbose_name='وثيقة الملكية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='properties.property', verbose_name='العقار')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_property_verifications', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي تحقق')),
            ],
            options={
                'verbose_name': 'تحقق عقار',
                'verbose_name_plural': 'تحققات العقارات',
            },
        ),
    ]
