# Generated by Django 5.2.17 on 2026-08-28 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0200_property_allows_companies_property_allows_families_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('property', 'عقار'), ('message', 'رسالة'), ('rating', 'تقييم'), ('subscription', 'اشتراك'), ('auction', 'مزاد'), ('building', 'بناء'), ('system', 'نظام'), ('verification', 'تحقق'), ('property_status', 'حالة عقار'), ('inquiry', 'استفسار')], default='info', max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('property', 'عقار'), ('message', 'رسالة'), ('rating', 'تقييم'), ('subscription', 'اشتراك'), ('auction', 'مزاد'), ('building', 'بناء'), ('system', 'نظام'), ('verification', 'تحقق'), ('property_status', 'حالة عقار'), ('inquiry', 'استفسار')], default='info', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['governorate'], name='properties__governo_61751e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose'], name='properties__purpose_ad2065_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['furnishing_status'], name='properties__furnish_113d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_condition'], name='properties__propert_365e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'purpose'], name='properties__status_b5886d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='properties__owner_i_9e1ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['broker'], name='properties__broker__f896ff_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['office'], name='properties__office__adfba2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['monthly_rent'], name='properties__monthly_e0d8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['views_count'], name='properties__views_c_030cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['complex_name'], name='properties__complex_d5f000_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['verification_status'], name='properties__verific_f2556f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['verified_by'], name='properties__verifie_a47b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['verification_date'], name='properties__verific_9cae0e_idx'),
        ),
    ]
