# Generated by Django 5.2.17 on 2026-08-28 23:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0201_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to='properties.conversation', verbose_name='المحادثة المرتبطة'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='converted_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة المحولة'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='first_contact',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='أول اتصال'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='interaction_count',
            field=models.IntegerField(default=0, verbose_name='عدد التفاعلات'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='تم التحويل'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='properties_interested',
            field=models.ManyToManyField(blank=True, related_name='interested_contacts', to='properties.property', verbose_name='العقارات المهتم بها'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف ثانوي'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'الموقع'), ('phone', 'الهاتف'), ('referral', 'إحالة'), ('social_media', 'وسائل التواصل'), ('property_inquiry', 'استفسار عقار'), ('walk_in', 'زيارة مباشرة'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط'),
        ),
        migrations.AlterField(
            model_name='crmcontact',
            name='priority',
            field=models.CharField(choices=[('hot', 'عالية'), ('warm', 'متوسطة'), ('cold', 'منخفضة')], default='warm', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='crmcontact',
            name='stage',
            field=models.CharField(choices=[('lead', 'عميل محتمل'), ('prospect', 'مرشح'), ('customer', 'عميل'), ('churned', 'سابق')], default='lead', max_length=20, verbose_name='المرحلة'),
        ),
        migrations.AlterField(
            model_name='crmcontact',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة المتوقعة'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['stage', 'priority'], name='properties__stage_c3de65_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['created_by'], name='properties__created_c83f40_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['assigned_to'], name='properties__assigne_95ef5c_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['next_followup'], name='properties__next_fo_a2a686_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['stage', '-created_at'], name='properties__stage_30ce4f_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['source'], name='properties__source_205ac0_idx'),
        ),
    ]
