# Generated by Django 5.2.17 on 2026-08-29 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0202_crmcontact_assigned_to_crmcontact_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='تجزئة الملف (SHA256)'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='الوسوم'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوثيق'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='وثق بواسطة'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'عام'), ('private', 'خاص'), ('authenticated', 'للمسجلين فقط')], default='private', max_length=20, verbose_name='الرؤية'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='نص بديل'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع (بكسل)'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منشورة'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='العرض (بكسل)'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منشور'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'قيد المعالجة'), ('processing', 'جاري المعالجة'), ('ready', 'جاهز'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة المعالجة'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, verbose_name='الدقة (مثال 1920x1080)'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='صورة مصغرة'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'document_type'], name='properties__propert_5d3698_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['uploaded_by'], name='properties__uploade_55fec8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['visibility'], name='properties__visibil_834b36_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['is_verified'], name='properties__is_veri_6b2412_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['expiry_date'], name='properties__expiry__6f946d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['-created_at'], name='properties__created_a193f7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'sort_order'], name='properties__propert_7883bd_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['is_primary'], name='properties__is_prim_893694_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['image_type'], name='properties__image_t_01c468_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['uploaded_by'], name='properties__uploade_1c85de_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['-created_at'], name='properties__created_d8b725_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['property', 'sort_order'], name='properties__propert_c2edc7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['video_type'], name='properties__video_t_1d341b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['uploaded_by'], name='properties__uploade_23df63_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['is_featured'], name='properties__is_feat_56b299_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['processing_status'], name='properties__process_104146_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['-created_at'], name='properties__created_6420d7_idx'),
        ),
    ]
