# Generated by Django 5.2.17 on 2026-08-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0203_propertydocument_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='additional_services',
            field=models.TextField(blank=True, verbose_name='خدمات إضافية'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='areas_served',
            field=models.TextField(blank=True, verbose_name='المناطق التي نخدمها'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_status',
            field=models.CharField(choices=[('available', 'متاح حالياً'), ('temporarily_stopped', 'متوقف مؤقتاً')], default='available', max_length=30, verbose_name='حالة العمل'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='catalog_pdf',
            field=models.FileField(blank=True, null=True, upload_to='service_providers/catalogs/', verbose_name='ملف PDF للأعمال'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة / القضاء'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='clients_count',
            field=models.IntegerField(default=0, verbose_name='عدد العملاء'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم التسجيل التجاري'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='نبذة عن الشركة'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='completed_projects_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاريع المنجزة'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='currency',
            field=models.CharField(choices=[('IQD', 'دينار عراقي'), ('USD', 'دولار')], default='IQD', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة / الحي'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='emergency_service',
            field=models.BooleanField(default=False, verbose_name='تقدم خدمة طوارئ'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تأسيس العمل'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='free_consultation',
            field=models.BooleanField(default=False, verbose_name='استشارة مجانية'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الجمعة'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='رابط Google Maps'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='home_service',
            field=models.BooleanField(default=False, verbose_name='تقدم خدمة منزلية'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='رابط إنستغرام'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الاثنين'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='السعر قابل للتفاوض'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='open_24_hours',
            field=models.BooleanField(default=False, verbose_name='مفتوح 24 ساعة'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المسؤول / صاحب العمل'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('individual', 'فردي'), ('company', 'شركة'), ('institution', 'مؤسسة')], max_length=20, verbose_name='نوع الملكية'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف إضافي'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='رابط معرض الأعمال'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('call', 'اتصال'), ('whatsapp', 'واتساب'), ('email', 'بريد')], max_length=20, verbose_name='أفضل وسيلة للتواصل'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='pricing_method',
            field=models.CharField(blank=True, choices=[('hourly', 'بالساعة'), ('per_meter', 'بالمتر'), ('per_project', 'بالمشروع'), ('per_piece', 'بالقطعة')], max_length=20, verbose_name='طريقة التسعير'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='السبت'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services_offered',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات التي يقدمها'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الأحد'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='team_skills',
            field=models.TextField(blank=True, verbose_name='التخصصات / مهارات الفريق'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الخميس'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='رابط تيك توك'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم التجاري'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الثلاثاء'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='رابط الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='الأربعاء'),
        ),
    ]
