# Generated by Django 5.2.17 on 2026-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0204_serviceprovider_additional_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='job',
            name='accept_recent_graduates',
            field=models.BooleanField(default=False, verbose_name='هل تقبل حديثي التخرج؟'),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_benefits',
            field=models.TextField(blank=True, verbose_name='بدلات/حوافز'),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_requirements',
            field=models.TextField(blank=True, verbose_name='متطلبات إضافية'),
        ),
        migrations.AddField(
            model_name='job',
            name='applicant_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات للمتقدم'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='آخر موعد للتقديم'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_method',
            field=models.CharField(blank=True, choices=[('call', 'اتصال'), ('whatsapp', 'واتساب'), ('email', 'بريد'), ('onsite', 'داخل الموقع')], max_length=20, verbose_name='طريقة التقديم'),
        ),
        migrations.AddField(
            model_name='job',
            name='available_for_students',
            field=models.BooleanField(default=False, verbose_name='هل الوظيفة متاحة للطلاب؟'),
        ),
        migrations.AddField(
            model_name='job',
            name='bonuses',
            field=models.BooleanField(default=False, verbose_name='مكافآت وحوافز'),
        ),
        migrations.AddField(
            model_name='job',
            name='commission',
            field=models.CharField(blank=True, max_length=100, verbose_name='عمولة'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_type',
            field=models.CharField(blank=True, choices=[('company', 'شركة'), ('institution', 'مؤسسة'), ('office', 'مكتب'), ('individual', 'فرد')], max_length=20, verbose_name='نوع جهة العمل'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
        migrations.AddField(
            model_name='job',
            name='day_off',
            field=models.CharField(blank=True, max_length=50, verbose_name='يوم العطلة'),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='القسم/التخصص'),
        ),
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء/المنطقة'),
        ),
        migrations.AddField(
            model_name='job',
            name='driving_license_required',
            field=models.BooleanField(default=False, verbose_name='رخصة قيادة'),
        ),
        migrations.AddField(
            model_name='job',
            name='driving_license_type',
            field=models.CharField(blank=True, choices=[('light', 'خفيفة'), ('heavy', 'ثقيلة'), ('motorcycle', 'دراجة نارية'), ('commercial', 'تجارية')], max_length=20, verbose_name='نوع رخصة القيادة'),
        ),
        migrations.AddField(
            model_name='job',
            name='education_specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص الدراسي'),
        ),
        migrations.AddField(
            model_name='job',
            name='enable_gps',
            field=models.BooleanField(default=False, verbose_name='نشر GPS - إظهار الموقع على خريطة المنصة'),
        ),
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.CharField(blank=True, max_length=100, verbose_name='المجال'),
        ),
        migrations.AddField(
            model_name='job',
            name='housing_provided',
            field=models.BooleanField(default=False, verbose_name='سكن'),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='مكان المقابلة'),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_method',
            field=models.CharField(blank=True, choices=[('in_person', 'حضوري'), ('online', 'أونلاين'), ('phone', 'هاتفي')], max_length=20, verbose_name='طريقة المقابلة'),
        ),
        migrations.AddField(
            model_name='job',
            name='language_level',
            field=models.CharField(blank=True, choices=[('basic', 'أساسي'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('fluent', 'طلاقة')], max_length=20, verbose_name='مستوى اللغة'),
        ),
        migrations.AddField(
            model_name='job',
            name='meals_provided',
            field=models.BooleanField(default=False, verbose_name='وجبات'),
        ),
        migrations.AddField(
            model_name='job',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='job',
            name='paid_vacations',
            field=models.BooleanField(default=False, verbose_name='إجازات مدفوعة'),
        ),
        migrations.AddField(
            model_name='job',
            name='promotion_opportunity',
            field=models.BooleanField(default=False, verbose_name='فرصة للترقية'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_certificates',
            field=models.TextField(blank=True, verbose_name='الشهادات المطلوبة'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_software',
            field=models.TextField(blank=True, verbose_name='البرامج/الأدوات المطلوبة'),
        ),
        migrations.AddField(
            model_name='job',
            name='training_development',
            field=models.BooleanField(default=False, verbose_name='تدريب وتطوير'),
        ),
        migrations.AddField(
            model_name='job',
            name='transport_provided',
            field=models.BooleanField(default=False, verbose_name='مواصلات'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_days',
            field=models.CharField(blank=True, max_length=100, verbose_name='أيام العمل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_name',
            field=models.CharField(max_length=100, verbose_name='اسم مسؤول التوظيف'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False, verbose_name='قابل للتفاوض'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='عاجل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_positions',
            field=models.IntegerField(default=1, verbose_name='عدد الشواغر'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hourly', 'بالساعة'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='طريقة دفع الراتب'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'منشور'), ('pending_review', 'قيد المراجعة'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='حالة الإعلان'),
        ),
    ]
