# Generated by Django 5.2.17 on 2026-08-30 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0205_remove_job_email_address_remove_job_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCompanyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان المنشور')),
                ('post_type', models.CharField(choices=[('trip', 'رحلة سياحية'), ('offer', 'عرض سفر'), ('ticket', 'تذكرة طيران'), ('hotel', 'فندق'), ('visa', 'تأشيرة'), ('umrah', 'عمرة'), ('hajj', 'حج'), ('transport', 'نقل سياحي'), ('general', 'إعلان عام'), ('special_offer', 'عرض خاص')], default='general', max_length=20, verbose_name='نوع المنشور')),
                ('description', models.TextField(verbose_name='وصف المنشور')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='travel_company_posts/', verbose_name='صورة المنشور')),
                ('external_link', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('departure_country', models.CharField(blank=True, max_length=100, verbose_name='بلد الانطلاق')),
                ('departure_city', models.CharField(blank=True, max_length=100, verbose_name='مدينة الانطلاق')),
                ('destination_country', models.CharField(blank=True, max_length=100, verbose_name='بلد الوصول')),
                ('destination_city', models.CharField(blank=True, max_length=100, verbose_name='مدينة الوصول')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأيام')),
                ('duration_nights', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الليالي')),
                ('persons_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأشخاص')),
                ('trip_type', models.CharField(blank=True, choices=[('one_way', 'ذهاب'), ('round_trip', 'ذهاب وعودة')], max_length=20, verbose_name='نوع الرحلة')),
                ('hotel_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الفندق')),
                ('hotel_stars', models.PositiveIntegerField(blank=True, null=True, verbose_name='تصنيف الفندق (نجوم)')),
                ('hotel_room_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الغرفة')),
                ('hotel_nights', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الليالي بالفندق')),
                ('includes_breakfast', models.BooleanField(default=False, verbose_name='وجبة الإفطار مشمولة')),
                ('includes_accommodation', models.BooleanField(default=False, verbose_name='الإقامة مشمولة')),
                ('airline', models.CharField(blank=True, max_length=200, verbose_name='شركة الطيران')),
                ('flight_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الرحلة')),
                ('flight_class', models.CharField(blank=True, choices=[('economy', 'اقتصادية'), ('business', 'رجال أعمال'), ('first', 'أولى')], max_length=20, verbose_name='درجة السفر')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر قبل الخصم')),
                ('currency', models.CharField(choices=[('IQD', 'دينار عراقي'), ('USD', 'دولار'), ('EUR', 'يورو'), ('TRY', 'ليرة تركية'), ('SAR', 'ريال سعودي')], default='IQD', max_length=10, verbose_name='العملة')),
                ('price_per', models.CharField(blank=True, max_length=50, verbose_name='السعر لـ (شخص/عائلة/غرفة)')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='قابل للتفاوض')),
                ('is_limited_offer', models.BooleanField(default=False, verbose_name='عرض لفترة محدودة')),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء العرض')),
                ('booking_method', models.CharField(choices=[('call', 'اتصال'), ('whatsapp', 'واتساب'), ('online', 'داخل الموقع'), ('external', 'رابط خارجي')], default='call', max_length=20, verbose_name='طريقة الحجز')),
                ('booking_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الحجز')),
                ('booking_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب الحجز')),
                ('booking_link', models.URLField(blank=True, verbose_name='رابط الحجز')),
                ('booking_deadline', models.DateField(blank=True, null=True, verbose_name='آخر موعد للحجز')),
                ('seats_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد المقاعد المتبقية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='properties.travelcompany', verbose_name='شركة السفر')),
            ],
            options={
                'verbose_name': 'منشور شركة سفر',
                'verbose_name_plural': 'منشورات شركات السفر',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelCompanyPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_company_posts/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.travelcompanypost', verbose_name='المنشور')),
            ],
            options={
                'verbose_name': 'صورة منشور',
                'verbose_name_plural': 'صور المنشورات',
                'ordering': ['order'],
            },
        ),
    ]
