# Generated by Django 5.2.17 on 2026-08-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0206_travelcompanypost_travelcompanypostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='average_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='متوسط سعر الليلة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='currency',
            field=models.CharField(default='د.ع', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='double_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الغرفة المزدوجة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='double_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف المزدوجة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='elevators',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد المصاعد'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='family_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الغرفة العائلية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='family_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف العائلية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الطوابق'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='إنستغرام'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='أقصى عدد للنزلاء'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر يصل إلى'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر يبدأ من'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='single_room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الغرفة الفردية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='single_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف الفردية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='suite_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الجناح'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='suites',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأجنحة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='تليغرام'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='total_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='triple_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف الثلاثية'),
        ),
        migrations.AddField(
            model_name='hotelpost',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_companies', to='properties.broker', verbose_name='الدلال'),
        ),
    ]
