# Generated by Django 5.2.17 on 2026-08-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0207_hotelpage_additional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='additional_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رسوم إضافية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='advance_booking_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد أيام الحجز المسبق'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='advance_booking_required',
            field=models.BooleanField(default=False, verbose_name='الحجز المسبق مطلوب'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='alley',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزقاق'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='beds_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأسرة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='block',
            field=models.CharField(blank=True, max_length=50, verbose_name='البلوك'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='booking_security',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='تأمين الحجز'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='cabins_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأكواخ'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='cancellation_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الإلغاء'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='chalets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الشاليهات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='child_safety',
            field=models.BooleanField(default=False, verbose_name='حماية للأطفال'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='children_friendly',
            field=models.BooleanField(default=False, verbose_name='مناسب للأطفال'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='children_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الأطفال'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='classification',
            field=models.CharField(blank=True, max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رسوم التنظيف'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='distance_to_airport',
            field=models.CharField(blank=True, max_length=100, verbose_name='المسافة إلى المطار'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='distance_to_city_center',
            field=models.CharField(blank=True, max_length=100, verbose_name='المسافة إلى وسط المدينة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='enable_gps',
            field=models.BooleanField(default=False, verbose_name='نشر GPS على خريطة المنصة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='establishment_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة التأسيس'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='extra_beds_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأسرة الإضافية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='extra_person_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الشخص الإضافي'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='family_friendly',
            field=models.BooleanField(default=False, verbose_name='مناسب للعائلات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='family_rooms_available',
            field=models.BooleanField(default=False, verbose_name='غرف خاصة للعائلات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='holiday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر أيام العطل'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الدار'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='includes_tax',
            field=models.BooleanField(default=False, verbose_name='الضرائب مشمولة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='is_outside_iraq',
            field=models.BooleanField(default=False, verbose_name='خارج العراق'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='kids_playground',
            field=models.BooleanField(default=False, verbose_name='منطقة ألعاب أطفال'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='kids_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح أطفال'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='licensing_authority',
            field=models.CharField(blank=True, max_length=200, verbose_name='جهة الترخيص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحلة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المدير'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='max_booking_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الحجز القصوى (أيام)'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='max_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأشخاص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='max_noise_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='الحد الأقصى للضوضاء'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='min_booking_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الحجز الدنيا (أيام)'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='min_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحد الأدنى للأشخاص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='min_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحد الأدنى للأشخاص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='music_allowed',
            field=models.BooleanField(default=False, verbose_name='يسمح بالموسيقى'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب مطار'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='nearest_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب مدينة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='nearest_metro_station',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب محطة مترو'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='nearest_train_station',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب محطة قطار'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المالك'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='parking_spaces',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد مواقف السيارات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='parties_allowed',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحفلات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الدفع'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='person_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الشخص'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر بعد الخصم'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر قبل الخصم'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_includes_services',
            field=models.BooleanField(default=False, verbose_name='السعر يشمل الخدمات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='price_negotiable',
            field=models.BooleanField(default=False, verbose_name='السعر قابل للتفاوض'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='property_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العقار'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='quiet_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='وقت الهدوء'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='refund_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الاسترداد'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ التأمين'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='services',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات والمميزات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد النجوم'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشارع'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, verbose_name='الناحية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='total_units',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الوحدات'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='tourist_area',
            field=models.CharField(blank=True, max_length=200, verbose_name='المنطقة السياحية'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر نهاية الأسبوع'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False, verbose_name='مرافق لذوي الإعاقة'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='governorate',
            field=models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='page_type',
            field=models.CharField(choices=[('hotel', 'فندق'), ('resort', 'منتجع'), ('chalet', 'شاليه'), ('cabin', 'كوخ'), ('guesthouse', 'بيت ضيافة'), ('inn', 'نُزل'), ('tourism_farm', 'مزرعة سياحية'), ('rest_house', 'استراحة'), ('camp', 'مخيم'), ('beach', 'شاطئ'), ('tourism_city', 'مدينة سياحية'), ('tourism_village', 'قرية سياحية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الصفحة'),
        ),
        migrations.AlterField(
            model_name='hotelpost',
            name='post_type',
            field=models.CharField(choices=[('listing', 'إعلان'), ('offer', 'عرض'), ('discount', 'خصم'), ('news', 'خبر'), ('event', 'مناسبة'), ('opening', 'افتتاح'), ('announcement', 'إعلان'), ('gallery', 'معرض صور'), ('video', 'فيديو'), ('tour_360', 'جولة 360°'), ('promotion', 'ترويج'), ('chalet_offer', 'عرض شاليه'), ('cabin_offer', 'عرض كوخ'), ('family_package', 'باقة عائلية'), ('honeymoon', 'شهر عسل'), ('night_offer', 'عرض ليلة'), ('week_offer', 'عرض أسبوع'), ('pool_offer', 'عرض مسبح'), ('bbq_offer', 'عرض شواء'), ('beach_offer', 'عرض شاطئ'), ('camping_offer', 'عرض تخييم'), ('activity', 'نشاط ترفيهي'), ('info', 'معلومات'), ('new_service', 'خدمة جديدة')], max_length=20, verbose_name='نوع المنشور'),
        ),
    ]
