# Generated by Django 5.2.17 on 2026-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0208_hotelpage_additional_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='service_type',
            field=models.CharField(max_length=100, verbose_name='نوع الخدمة'),
        ),
    ]
