# Generated by Django 5.2.17 on 2026-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0209_alter_serviceadvertisement_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
    ]
