# Generated by Django 5.2.17 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0210_alter_serviceadvertisement_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_auctions_premium',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للمزادات المميزة'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_auctions_regular',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للمزادات العادية'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_hotels',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للفنادق'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_jobs',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للوظائف'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_properties_premium',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للعقارات المميزة'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_properties_regular',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للعقارات العادية'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_resorts',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للمنتجعات'),
        ),
        migrations.AddField(
            model_name='advancedsubscriptionplan',
            name='max_services',
            field=models.IntegerField(default=0, verbose_name='الحد الأقصى للخدمات'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='auctions_premium_used',
            field=models.IntegerField(default=0, verbose_name='المزادات المميزة المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='auctions_regular_used',
            field=models.IntegerField(default=0, verbose_name='المزادات العادية المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='hotels_used',
            field=models.IntegerField(default=0, verbose_name='الفنادق المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='jobs_used',
            field=models.IntegerField(default=0, verbose_name='الوظائف المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='properties_premium_used',
            field=models.IntegerField(default=0, verbose_name='العقارات المميزة المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='properties_regular_used',
            field=models.IntegerField(default=0, verbose_name='العقارات العادية المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='resorts_used',
            field=models.IntegerField(default=0, verbose_name='المنتجعات المستخدمة'),
        ),
        migrations.AddField(
            model_name='brokerplansubscription',
            name='services_used',
            field=models.IntegerField(default=0, verbose_name='الخدمات المستخدمة'),
        ),
    ]
