# Generated by Django 5.2.17 on 2026-09-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0212_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='السعر (د.ع)'),
        ),
    ]
