# Generated by Django 5.2.17 on 2026-09-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0213_alter_property_area_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='virtual_tour_video',
            field=models.FileField(blank=True, null=True, upload_to='hotel_pages/virtual_tours/', verbose_name='جولة افتراضية 360°'),
        ),
    ]
