# Generated by Django 5.2.17 on 2026-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0214_hotelpage_virtual_tour_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpage',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='hotel_pages/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الصفحة'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to='hotel_pages/logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الصفحة'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
