# Generated by Django 5.2.17 on 2026-09-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0216_alter_hotelpage_alley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الإعلان'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الإعلان'),
        ),
    ]
