# Generated by Django 5.2.17 on 2026-09-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0219_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotelpage',
            name='idx_hotel_status_created',
        ),
        migrations.RemoveIndex(
            model_name='hotelpage',
            name='idx_hotel_location',
        ),
        migrations.RemoveIndex(
            model_name='hotelpage',
            name='idx_hotel_type_location',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_status',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_type',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_purpose',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_governorate',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_city',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_category',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_created_at',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_featured',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_verified',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_status_created',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_location',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_type_purpose',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_broker',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_owner',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='idx_property_image_primary',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='idx_property_image_sort',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تغيير لكلمة المرور'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='virtual_tours/audio/', verbose_name='ملف الصوت'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='background_music',
            field=models.BooleanField(default=False, verbose_name='موسيقى خلفية'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_audio',
            field=models.BooleanField(default=False, verbose_name='تفعيل الصوت'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_compass',
            field=models.BooleanField(default=True, verbose_name='تفعيل البوصلة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_hotspots',
            field=models.BooleanField(default=False, verbose_name='تفعيل النقاط الساخنة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_minimap',
            field=models.BooleanField(default=False, verbose_name='تفعيل الخريطة المصغرة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='interaction_count',
            field=models.IntegerField(default=0, verbose_name='عدد التفاعلات'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مشاهدة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='loading_animation',
            field=models.BooleanField(default=True, verbose_name='تحميل متحرك'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='resolution',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('ultra', 'فائقة الجودة')], default='medium', max_length=20, verbose_name='دقة الصورة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='virtual_tours/thumbnails/', verbose_name='صورة مصغرة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='transition_effect',
            field=models.CharField(choices=[('fade', 'تلاشي'), ('slide', 'انزلاق'), ('zoom', 'تكبير'), ('none', 'بدون تأثير')], default='fade', max_length=20, verbose_name='تأثير الانتقال'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='virtualtour360',
            name='external_service',
            field=models.CharField(blank=True, choices=[('matterport', 'Matterport'), ('kuula', 'Kuula'), ('google', 'Google Street View'), ('panoskin', 'Panoskin'), ('cupix', 'Cupix'), ('other', 'خدمة أخرى')], max_length=20, verbose_name='خدمة خارجية'),
        ),
        migrations.AlterField(
            model_name='virtualtour360',
            name='tour_type',
            field=models.CharField(choices=[('image', 'صورة بانورامية 360°'), ('file', 'ملف جولة 360° جاهز'), ('external', 'رابط خارجي'), ('multi', 'جولة من عدة صور مترابطة'), ('video', 'فيديو 360°')], default='image', max_length=20, verbose_name='نوع الجولة'),
        ),
    ]
