# Generated by Django 5.2.17 on 2026-09-04 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0220_remove_hotelpage_idx_hotel_status_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='enable_notifications',
            field=models.BooleanField(default=False, verbose_name='تفعيل الإشعارات'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر إشعار'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='search_type',
            field=models.CharField(default='property', max_length=20, verbose_name='نوع البحث'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_87aa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['search_type'], name='properties__search__fc28c5_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['enable_notifications'], name='properties__enable__b0d348_idx'),
        ),
    ]
