# Generated by Django 5.2.17 on 2026-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0221_savedsearch_enable_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المرفق')),
                ('amenity_type', models.CharField(choices=[('school', 'مدرسة'), ('hospital', 'مستشفى'), ('clinic', 'عيادة'), ('university', 'جامعة'), ('market', 'سوق'), ('mall', 'مول تجاري'), ('supermarket', 'سوبرماركت'), ('mosque', 'مسجد'), ('church', 'كنيسة'), ('park', 'حديقة'), ('gas_station', 'محطة وقود'), ('bank', 'بنك'), ('atm', 'صراف آلي'), ('pharmacy', 'صيدلية'), ('restaurant', 'مطعم'), ('cafe', 'مقهى'), ('gym', 'نادي رياضي'), ('airport', 'مطار'), ('train_station', 'محطة قطار'), ('bus_station', 'محطة حافلات'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المرفق')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='التقييم')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='ساعات العمل')),
                ('education_level', models.CharField(blank=True, max_length=50, verbose_name='المستوى التعليمي')),
                ('student_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الطلاب')),
                ('bed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأسرة')),
                ('emergency_services', models.BooleanField(default=False, verbose_name='خدمات الطوارئ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرافق والخدمات',
                'indexes': [models.Index(fields=['amenity_type'], name='properties__amenity_b8348a_idx'), models.Index(fields=['governorate', 'city'], name='properties__governo_a0f678_idx'), models.Index(fields=['latitude', 'longitude'], name='properties__latitud_a86afa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AreaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('bounds_south', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='الحد الجنوبي')),
                ('bounds_north', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='الحد الشمالي')),
                ('bounds_west', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='الحد الغربي')),
                ('bounds_east', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='الحد الشرقي')),
                ('avg_price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='متوسط السعر لكل م²')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='متوسط السعر')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='أقل سعر')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='أعلى سعر')),
                ('total_properties', models.PositiveIntegerField(default=0, verbose_name='إجمالي العقارات')),
                ('sale_properties', models.PositiveIntegerField(default=0, verbose_name='عقارات البيع')),
                ('rent_properties', models.PositiveIntegerField(default=0, verbose_name='عقارات الإيجار')),
                ('price_trend', models.CharField(choices=[('rising', 'ارتفاع'), ('falling', 'انخفاض'), ('stable', 'مستقر')], default='stable', max_length=20, verbose_name='اتجاه السعر')),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة تغير السعر')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='عدد المفضلات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إحصائيات المنطقة',
                'verbose_name_plural': 'إحصائيات المناطق',
                'indexes': [models.Index(fields=['governorate', 'city'], name='properties__governo_488ae2_idx'), models.Index(fields=['avg_price'], name='properties__avg_pri_c4f704_idx'), models.Index(fields=['price_trend'], name='properties__price_t_bed66a_idx'), models.Index(fields=['-updated_at'], name='properties__updated_69d522_idx')],
                'unique_together': {('governorate', 'city', 'district', 'area')},
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('lat_min', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض الأدنى')),
                ('lat_max', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض الأقصى')),
                ('lng_min', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول الأدنى')),
                ('lng_max', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول الأقصى')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الكثافة')),
                ('property_count', models.PositiveIntegerField(default=0, verbose_name='عدد العقارات')),
                ('property_type', models.CharField(blank=True, max_length=50, verbose_name='نوع العقار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'بيانات الخريطة الحرارية',
                'verbose_name_plural': 'بيانات الخرائط الحرارية',
                'indexes': [models.Index(fields=['governorate', 'city'], name='properties__governo_dd9284_idx'), models.Index(fields=['lat_min', 'lat_max', 'lng_min', 'lng_max'], name='properties__lat_min_d9b2e3_idx'), models.Index(fields=['-value'], name='properties__value_a87cb4_idx')],
            },
        ),
    ]
