# Generated by Django 5.2.17 on 2026-09-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0223_alter_pushsubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotelroom',
            name='properties__floor_71ad2e_idx',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='floor_plan_height',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='floor_plan_rotation',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='floor_plan_width',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='floor_plan_x',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='floor_plan_y',
        ),
    ]
