# Generated by Django 5.2.17 on 2026-09-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0224_remove_hotelroom_properties__floor_71ad2e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الحد الأدنى للميزانية')),
                ('max_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الحد الأقصى للميزانية')),
                ('currency', models.CharField(default='د.ع', max_length=10, verbose_name='العملة')),
                ('search_type', models.CharField(choices=[('purchase', 'شراء'), ('rent', 'إيجار'), ('investment', 'استثمار')], default='purchase', max_length=20, verbose_name='نوع البحث')),
                ('property_type', models.CharField(choices=[('all', 'الكل'), ('residential', 'سكني'), ('commercial', 'تجاري'), ('land', 'أرض'), ('villa', 'فيلا'), ('apartment', 'شقة'), ('shop', 'محل'), ('office', 'مكتب')], default='all', max_length=20, verbose_name='نوع العقار')),
                ('governorate', models.CharField(blank=True, default='', max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('include_all_iraq', models.BooleanField(default=True, verbose_name='شمل كل العراق')),
                ('min_area', models.IntegerField(blank=True, null=True, verbose_name='الحد الأدنى للمساحة')),
                ('max_area', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمساحة')),
                ('min_bedrooms', models.IntegerField(blank=True, null=True, verbose_name='الحد الأدنى للغرف')),
                ('max_bedrooms', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للغرف')),
                ('expected_roi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='العائد المتوقع %')),
                ('investment_period', models.IntegerField(blank=True, default=0, null=True, verbose_name='فترة الاستثمار (سنوات)')),
                ('results_count', models.IntegerField(default=0, verbose_name='عدد النتائج')),
                ('recommended_properties', models.JSONField(blank=True, default=list, verbose_name='العقارات الموصى بها')),
                ('is_saved', models.BooleanField(default=False, verbose_name='محفوظ')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='مفضل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البحث')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_searches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بحث ميزانية',
                'verbose_name_plural': 'عمليات البحث بالميزانية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_e393ab_idx'), models.Index(fields=['search_type'], name='properties__search__2501ab_idx'), models.Index(fields=['min_budget', 'max_budget'], name='properties__min_bud_99a6b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رأس المال')),
                ('currency', models.CharField(default='د.ع', max_length=10, verbose_name='العملة')),
                ('investment_type', models.CharField(choices=[('rental', 'إيجاري'), ('flip', 'شراء وبيع'), ('development', 'تطوير'), ('commercial', 'تجاري')], max_length=20, verbose_name='نوع الاستثمار')),
                ('investment_period', models.IntegerField(default=1, verbose_name='فترة الاستثمار (سنوات)')),
                ('expected_roi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='العائد المتوقع %')),
                ('risk_tolerance', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=20, verbose_name='تحمل المخاطرة')),
                ('preferred_locations', models.JSONField(blank=True, default=list, verbose_name='المناطق المفضلة')),
                ('estimated_return', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='العائد المقدر')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='الدخل الشهري المقدر')),
                ('recommended_properties', models.JSONField(blank=True, default=list, verbose_name='العقارات الموصى بها')),
                ('is_saved', models.BooleanField(default=False, verbose_name='محفوظ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحساب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_calculations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حاسبة استثمار',
                'verbose_name_plural': 'حاسبات الاستثمار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_7079c0_idx'), models.Index(fields=['investment_type'], name='properties__investm_cf4515_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region1_governorate', models.CharField(default='', max_length=100, verbose_name='المحافظة الأولى')),
                ('region1_city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة الأولى')),
                ('region2_governorate', models.CharField(default='', max_length=100, verbose_name='المحافظة الثانية')),
                ('region2_city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة الثانية')),
                ('comparison_type', models.CharField(choices=[('prices', 'الأسعار'), ('rentals', 'الإيجارات'), ('services', 'الخدمات'), ('investment', 'الاستثمار'), ('all', 'الكل')], default='all', max_length=20, verbose_name='نوع المقارنة')),
                ('property_type', models.CharField(blank=True, default='', max_length=20, verbose_name='نوع العقار')),
                ('comparison_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات المقارنة')),
                ('recommendation', models.TextField(blank=True, default='', verbose_name='التوصية')),
                ('is_saved', models.BooleanField(default=False, verbose_name='محفوظ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المقارنة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_comparisons', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقارنة مناطق',
                'verbose_name_plural': 'مقارنات المناطق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_5c44b5_idx'), models.Index(fields=['region1_governorate', 'region2_governorate'], name='properties__region1_8ed011_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartPropertyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الدرجة الكلية')),
                ('score_level', models.CharField(choices=[('excellent', 'ممتاز (90-100)'), ('very_good', 'جيد جداً (80-89)'), ('good', 'جيد (70-79)'), ('fair', 'مقبول (60-69)'), ('poor', 'ضعيف (أقل من 60)')], default='fair', max_length=20, verbose_name='مستوى التقييم')),
                ('price_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة السعر')),
                ('location_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة الموقع')),
                ('area_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة المساحة')),
                ('amenities_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة المميزات')),
                ('condition_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة الحالة')),
                ('verification_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مكافأة التحقق')),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة الشعبية')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل التقييم')),
                ('improvement_suggestions', models.JSONField(blank=True, default=list, verbose_name='اقتراحات التحسين')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر حساب')),
                ('calculation_version', models.CharField(default='1.0', max_length=10, verbose_name='إصدار الحساب')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_score', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'تقييم ذكي',
                'verbose_name_plural': 'التقييمات الذكية',
                'indexes': [models.Index(fields=['overall_score'], name='properties__overall_127cae_idx'), models.Index(fields=['score_level'], name='properties__score_l_17b10c_idx')],
            },
        ),
    ]
