# Generated by Django 5.2.17 on 2026-09-04 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0225_budgetsearch_investmentcalculator_regioncomparison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='السعر الابتدائي')),
                ('currency', models.CharField(default='IQD', max_length=3, verbose_name='العملة')),
                ('current_buyer_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر المشتري الحالي')),
                ('current_seller_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر البائع الحالي')),
                ('price_gap', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='فجوة السعر')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='السعر المستهدف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('rounds', models.PositiveIntegerField(default=1, verbose_name='جولات المفاوضة')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='السعر النهائي')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='properties.property', verbose_name='العقار')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'مفاوضة عقار',
                'verbose_name_plural': 'مفاوضات العقارات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('offer', 'عرض سعر'), ('counter', 'عرض مضاد'), ('info', 'معلومات'), ('question', 'سؤال'), ('system', 'نظام')], max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='السعر المقدم')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.propertynegotiation', verbose_name='المفاوضة')),
            ],
            options={
                'verbose_name': 'رسالة مفاوضة',
                'verbose_name_plural': 'رسائل المفاوضات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='السعر المقدم')),
                ('currency', models.CharField(default='IQD', max_length=3, verbose_name='العملة')),
                ('message', models.TextField(blank=True, verbose_name='رسالة العرض')),
                ('financing_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة التمويل')),
                ('down_payment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الدفعة المقدمة')),
                ('payment_timeline', models.CharField(blank=True, max_length=100, verbose_name='الجدول الزمني للدفع')),
                ('contingencies', models.JSONField(blank=True, default=list, verbose_name='الشروط الخاصة')),
                ('valid_until', models.DateTimeField(verbose_name='صالح حتى')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='عرض حصري')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('countered', 'عرض مضاد'), ('expired', 'منتهي الصلاحية'), ('withdrawn', 'مسحوب')], default='pending', max_length=20, verbose_name='الحالة')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('response_message', models.TextField(blank=True, verbose_name='رسالة الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_offers', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'عرض عقار',
                'verbose_name_plural': 'عروض العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(default='viewing', max_length=50, verbose_name='نوع الحجز')),
                ('duration_hours', models.PositiveIntegerField(default=24, verbose_name='مدة الحجز بالساعات')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('visit_purpose', models.TextField(verbose_name='غرض الزيارة')),
                ('preferred_date', models.DateField(verbose_name='التاريخ المفضل')),
                ('preferred_time', models.TimeField(verbose_name='الوقت المفضل')),
                ('number_of_visitors', models.PositiveIntegerField(default=1, verbose_name='عدد الزوار')),
                ('special_requirements', models.TextField(blank=True, verbose_name='متطلبات خاصة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('expired', 'منتهي الصلاحية'), ('converted', 'محول لعرض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رسوم الحجز')),
                ('fee_paid', models.BooleanField(default=False, verbose_name='تم دفع الرسوم')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reservations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز عقار',
                'verbose_name_plural': 'حجوزات العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('info', 'معلومات'), ('reminder', 'تذكير'), ('cancellation', 'إلغاء'), ('change', 'تغيير'), ('followup', 'متابعة')], max_length=20, verbose_name='نوع الملاحظة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='properties.propertyreservation', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'ملاحظة حجز',
                'verbose_name_plural': 'ملاحظات الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertynegotiation',
            index=models.Index(fields=['property_obj', '-created_at'], name='properties__propert_e1ce9f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertynegotiation',
            index=models.Index(fields=['buyer', '-created_at'], name='properties__buyer_i_68c9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertynegotiation',
            index=models.Index(fields=['seller', '-created_at'], name='properties__seller__2b5df4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertynegotiation',
            index=models.Index(fields=['status', '-updated_at'], name='properties__status_15d3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationmessage',
            index=models.Index(fields=['negotiation', '-created_at'], name='properties__negotia_efe646_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationmessage',
            index=models.Index(fields=['sender', '-created_at'], name='properties__sender__e8ae84_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationmessage',
            index=models.Index(fields=['is_read'], name='properties__is_read_dce7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffer',
            index=models.Index(fields=['property_obj', '-created_at'], name='properties__propert_6e9db5_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffer',
            index=models.Index(fields=['buyer', '-created_at'], name='properties__buyer_i_0f728d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffer',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_f7f391_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyoffer',
            index=models.Index(fields=['valid_until'], name='properties__valid_u_7fca44_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreservation',
            index=models.Index(fields=['property_obj', '-created_at'], name='properties__propert_661433_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreservation',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_38e5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreservation',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_cf057e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreservation',
            index=models.Index(fields=['expires_at'], name='properties__expires_9b5ed1_idx'),
        ),
    ]
