# Generated by Django 5.2.17 on 2026-09-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0226_propertynegotiation_negotiationmessage_propertyoffer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'متصل'), ('offline', 'غير متصل'), ('away', 'غير متاح'), ('busy', 'مشغول')], default='offline', max_length=20, verbose_name='الحالة')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('is_typing', models.BooleanField(default=False, verbose_name='يكتب حالياً')),
            ],
            options={
                'verbose_name': 'حالة المستخدم المتصلة',
                'verbose_name_plural': 'حالات المستخدمين المتصلة',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'مرسلة'), ('delivered', 'مستلمة'), ('read', 'مقروءة'), ('failed', 'فشلت')], default='sent', max_length=20, verbose_name='حالة الرسالة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف'), ('location', 'موقع'), ('property', 'عقار'), ('hotel', 'فندق'), ('resort', 'منتجع'), ('system', 'نظام')], default='text', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_b8f14f_idx'),
        ),
        migrations.AddField(
            model_name='useronlinestatus',
            name='typing_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_users', to='properties.conversation', verbose_name='المحادثة التي يكتب فيها'),
        ),
        migrations.AddField(
            model_name='useronlinestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['status', '-last_activity'], name='properties__status_83881c_idx'),
        ),
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['-last_activity'], name='properties__last_ac_3cd42c_idx'),
        ),
    ]
