# Generated by Django 5.2.17 on 2026-09-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0227_useronlinestatus_chatmessage_delivered_at_and_more'),
        ('properties', '0231_activitylog'),
    ]

    operations = [
    ]
