# Generated by Django 5.2.17 on 2026-09-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_fix_duplicate_slug_index'),
        ('properties', '0232_merge_20260908_2320'),
    ]

    operations = [
    ]
