# Generated by Django 5.2.17 on 2026-09-14
# Skip migration 0234 that fails due to missing property_id column in Railway database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0233_merge_20260910_0503'),
    ]

    operations = [
        # No operations - this migration replaces 0234_add_subscription_to_property
        # which failed due to trying to remove a non-existent property_id column
        # The subscription fields will be added in a future migration if needed
    ]
