# Generated by Django 5.2.17 on 2026-09-14
# No-op migration to fix Railway deployment issue

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0233_merge_20260910_0503'),
    ]

    operations = [
        # No operations - migration exists but does nothing
    ]
