# Generated by Django 5.2.17 on 2026-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0234_add_subscription_to_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد'), ('approve', 'موافقة'), ('reject', 'رفض'), ('suspend', 'إيقاف'), ('activate', 'تفعيل'), ('renew', 'تجديد'), ('message', 'رسالة'), ('notification', 'إشعار'), ('published', 'نشر')], max_length=20, verbose_name='الإجراء'),
        ),
    ]
