# Generated by Django 5.2.17 on 2026-09-14
# Add subscription fields to property model (from 0234 that was made no-op)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0235_alter_activitylog_action'),
    ]

    operations = [
        # Add subscription fields using SQL to handle if they already exist
        migrations.RunSQL(
            sql=[
                # Add is_subscription_based column if it doesn't exist
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_property' AND column_name = 'is_subscription_based') THEN ALTER TABLE properties_property ADD COLUMN is_subscription_based BOOLEAN DEFAULT FALSE; END IF; END $$",
                # Add subscription_id column if it doesn't exist
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_property' AND column_name = 'subscription_id') THEN ALTER TABLE properties_property ADD COLUMN subscription_id INTEGER NULL; END IF; END $$",
                # Add theme_mode column to sitesettings if it doesn't exist
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_sitesettings' AND column_name = 'theme_mode') THEN ALTER TABLE properties_sitesettings ADD COLUMN theme_mode VARCHAR(10) DEFAULT 'light'; END IF; END $$",
                # Add auctionparticipant fields if they don't exist
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_auctionparticipant' AND column_name = 'approval_status') THEN ALTER TABLE properties_auctionparticipant ADD COLUMN approval_status VARCHAR(20) DEFAULT 'pending'; END IF; END $$",
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_auctionparticipant' AND column_name = 'approved_at') THEN ALTER TABLE properties_auctionparticipant ADD COLUMN approved_at TIMESTAMP NULL; END IF; END $$",
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_auctionparticipant' AND column_name = 'approved_by_id') THEN ALTER TABLE properties_auctionparticipant ADD COLUMN approved_by_id INTEGER NULL; END IF; END $$",
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_auctionparticipant' AND column_name = 'rejection_reason') THEN ALTER TABLE properties_auctionparticipant ADD COLUMN rejection_reason TEXT NULL; END IF; END $$",
                # Add broker suspension_reason if it doesn't exist
                "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties_broker' AND column_name = 'suspension_reason') THEN ALTER TABLE properties_broker ADD COLUMN suspension_reason VARCHAR(200) NULL; END IF; END $$",
            ],
            reverse_sql=[
                "ALTER TABLE properties_property DROP COLUMN IF EXISTS is_subscription_based",
                "ALTER TABLE properties_property DROP COLUMN IF EXISTS subscription_id",
                "ALTER TABLE properties_sitesettings DROP COLUMN IF EXISTS theme_mode",
                "ALTER TABLE properties_auctionparticipant DROP COLUMN IF EXISTS approval_status",
                "ALTER TABLE properties_auctionparticipant DROP COLUMN IF EXISTS approved_at",
                "ALTER TABLE properties_auctionparticipant DROP COLUMN IF EXISTS approved_by_id",
                "ALTER TABLE properties_auctionparticipant DROP COLUMN IF EXISTS rejection_reason",
                "ALTER TABLE properties_broker DROP COLUMN IF EXISTS suspension_reason",
            ],
        ),
    ]
