# Generated by Django 5.2.17 on 2026-09-10 14:28
# Fixed: 2026-09-14 - Handle duplicate user_type column gracefully

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0236_classify_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='هل هذه الوثيقة هي الأساسية لنوعها؟', verbose_name='أساسي'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='party_type',
            field=models.CharField(blank=True, choices=[('buyer', 'المشتري'), ('seller', 'البائع'), ('broker', 'الدلال'), ('witness', 'الشاهد'), ('other', 'طرف آخر')], help_text='الطرف المرتبط بالوثيقة (للصور الشخصية)', max_length=20, verbose_name='الطرف'),
        ),
        # Fix: Handle user_type column that may already exist
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='user_type',
                    field=models.CharField(choices=[('user', 'مستخدم عادي'), ('broker', 'دلال'), ('admin', 'مدير')], default='user', max_length=10, verbose_name='نوع المستخدم'),
                ),
            ],
            database_operations=[
                # Only add if column doesn't exist
                migrations.RunSQL(
                    sql="ALTER TABLE properties_userprofile ADD COLUMN IF NOT EXISTS user_type VARCHAR(10) DEFAULT 'user'",
                    reverse_sql="ALTER TABLE properties_userprofile DROP COLUMN IF EXISTS user_type",
                ),
            ],
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'العقد الأصلي'), ('contract_page', 'صفحة عقد'), ('personal_photo', 'صورة شخصية'), ('addendum', 'مذكرة إضافة'), ('amendment', 'تعديل'), ('receipt', 'إيصال'), ('invoice', 'فاتورة'), ('id_copy', 'صورة الهوية'), ('property_docs', 'وثائق العقار'), ('payment_proof', 'إثبات دفع'), ('other', 'وثيقة أخرى')], max_length=20, verbose_name='نوع الوثيقة'),
        ),
    ]
