# Generated by Django 5.2.17 on 2026-09-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_fix_notification_property_column'),
        ('properties', '0237_contractdocument_is_primary_and_more'),
    ]

    operations = [
    ]
